### ISSUE TITLE
Editace výstav - nahrávání souborů

### ISSUE THREAD

**Issue by krizovj** [LIBCAS/INDIHU#1]
Poznámka ze schůzky 25. 4. 2018

Nemělo by být možné nahrát soubor s názvem, který již v úložišti existuje. V takovém případě se název změní automatickým přidáním čísla.

**Comment by rudky4** [comment]
Automatické premenovanie resp. doplnenie čísla do názvu súboru.

**Comment by rudky4** [comment]
Automatické premenovanie resp. doplnenie čísla do názvu súboru je pridané.
file.png... dalsi upload: file_1.png
