### ISSUE TITLE
Na úvodní obrazovce se zobrazuje zbytečný scrollbar

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU#10]
Úvodní obrazovka -> více informací -> zobrazeny jsou zbytečné scrollbary, i když nejsou k ničemu potřeba:

![image](https://user-images.githubusercontent.com/20186892/43641840-6ca24e7e-9725-11e8-8eef-45325de5ffee.png)

**Comment by rudky4** [comment]
Zobrazenie obsahu využíva celú dostupnú plochu a scrollbary sa už zbytočne nezobrazujú.

![image](https://user-images.githubusercontent.com/7311447/43900888-5c0162f6-9be6-11e8-86d7-713d6aa146a8.png)

Prosím o test a prípadné uzavretie.
