### ISSUE TITLE
Nevhodné pojmenování polí pro nahrávání zvukových stop

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU#12]
Momentálně se na úvodní obrazovce kapitoly vyskytují pole "Mluvené slovo" a "Hudební podkres obrazovky". Přitom by však mělo jít spíše o "Zvuková stopa kapitoly" a "Zvuková stopa obrazovky". Co bude obsahem je na autorovi výstavy a navíc je takové označení matoucí, protože neříká nic o tom, kde se zvuk přehraje. Nekoresponduje to ani s manuálem (viz http://inqooltest.libj.cas.cz/manual/), kde se píše že: "Zvuková stopa pro celou kapitolu je přehrávána ve smyčce počas průchodu všemi stránkami kapitoly. Zvuková stopa pro úvodní stránku kapitoly je přehrána pouze jednou a definuje svou délkou i délku animace obrázku a celkově délku setrvání na této stránce při prohlížení v prezentačním módu.". Formulář tomu ale neodpovídá.

Pokud navíc jako kapitolu nastavím běžnou obrazovku, zobrazuje se dvakrát pole "Hudební podkres obrazovky".
![image](https://user-images.githubusercontent.com/20186892/43642400-a7c1b2a4-9727-11e8-80d9-8c7304ae55a9.png)

**Comment by rudky4** [comment]
Opraveno dle zadani. Prosim o test @motyc

**Comment by motyc** [comment]
U kapitol je to ok, ale ještě bych uvedl s tímto do souladu stránku obrazovky, kde je stále psáno "mluvené slovo":
![image](https://user-images.githubusercontent.com/20186892/43902189-bb4864f0-9be9-11e8-99d1-26245401c72a.png)

**Comment by rudky4** [comment]
@motyc upravíme

**Comment by rudky4** [comment]
U obrazovek chcete nahradit "Mluvené slovo" za "Zvuková stopa obrazovky" = OK 
Ale u samostatných obrazovek (které nejsou v rámci kapitoly) je pole "Mluvené slovo" i pole "Hudební podkres obrazovky", které by se podle předchozího mělo přejmenovat taky na "Zvuková stopa obrazovky"... takže to bude chtít asi jiné pojmenování

**Comment by motyc** [comment]
Shrnuji dohodu s dnešní schůzky:
- kapitola = Zvuková stopa kapitoly + Zvuková stopa obrazovky
- obrazovka = Zvuková stopa obrazovky
- obrazovka jako kapitola = Zvuková stopa obrazovky

**Comment by rudky4** [comment]
Upraveno, bude ok
