### ISSUE TITLE
Šipka mezi stránkami výstavy

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU#15]
Šipka pro posouvání mezi jednotlivými stránkami výstavy v náhledovém zobrazení je nyní celá bílá - tudíž na obrázku s čistě bílým pozadím zaniká. Za ARUP navrhujeme přidat šipce černé ohraničení.

**Comment by rudky4** [comment]
Implementavano

**Comment by Kolemkoukolem** [comment]
V praxi se ukázalo, že šipky je potřeba zvýraznit ještě více - viz příklady, kde zanikají:
![Obrázek14](https://user-images.githubusercontent.com/42067492/70153755-bfbace00-16af-11ea-9fc8-87afc02a5a3d.jpg)
![Obrázek13](https://user-images.githubusercontent.com/42067492/70153757-c1849180-16af-11ea-9bd6-9ace0d5e1a65.jpg)
![Obrázek12](https://user-images.githubusercontent.com/42067492/70153761-c2b5be80-16af-11ea-8939-92f7ffe6d5ec.jpg)
