### ISSUE TITLE
Podnázev

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU#16]
V náhledu úvodu do kapitoly se nezobrazuje podnázev:

![obrazek](https://user-images.githubusercontent.com/42067492/43718370-be196938-998a-11e8-9aff-2bc93215bb9b.png)

![obrazek](https://user-images.githubusercontent.com/42067492/43718378-c4f66ce2-998a-11e8-88ca-80147e04406f.png)

**Comment by rudky4** [comment]
@Kolemkoukolem opraveno, prosím o test a prípadne uzavretie.

![image](https://user-images.githubusercontent.com/7311447/43902675-fe359106-9bea-11e8-81b0-b433a7c65deb.png)
