### ISSUE TITLE
Popis infopointu ve fotogalerii

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU#18]
Při vkládání nového textu do popisu infopointu se musí celý informativní text ("Vložte popis infopointu") označit a smazat. Ideální by bylo, kdyby po kliknutí automaticky zmizel. 

![obrazek](https://user-images.githubusercontent.com/42067492/43725174-187507e6-999c-11e8-8a7d-47fb9e1bfb51.png)

Dále bych přivítal, kdyby se okno textu infopointu při editaci zvětšovalo souměrně s napsaným textem. V současnosti nelze přehlídnout celý napsaný text, což snižuje přehlednost při opravování chyb či překlepů.

![obrazek](https://user-images.githubusercontent.com/42067492/43725156-0916de50-999c-11e8-9af8-91b8f9b57595.png)

**Comment by rudky4** [comment]
- text sa automaticky po kliku na pole zmaže
- veľkosť pole je kvôli layoutu aktuálne fixná

**Comment by Kolemkoukolem** [comment]
Stávající řešení mi nejpřijde ideální. Informativní text ("Vložte popis infopointu") se dle mého požadavku automaticky smaže - to je v pořádku. Bohužel se smaže i jakýkoli starší text v již vyplněném infopointu po kliknutí na něj. Nelze se tedy ke stávajícímu textu vrátit a editovat ho.

**Comment by rudky4** [comment]
@Kolemkoukolem upravime

**Comment by rudky4** [comment]
@Kolemkoukolem upravené, prosím o test

**Comment by Kolemkoukolem** [comment]
Funguje. Díky.
