### ISSUE TITLE
Nahrávání souboru

### ISSUE THREAD

**Issue by krizovj** [LIBCAS/INDIHU#2]
Když chci nahrát obrázek nebo audioverzi výstavy, v okně pro nahrání souboru je možné nahrát nový soubor:
![nahratobrazek](https://user-images.githubusercontent.com/21309201/42813359-04cf53da-89c1-11e8-87d9-292567c40bd4.jpg)

Ale u dokumentu tato funkce není, šlo by ji tam přidat?
![nahrat](https://user-images.githubusercontent.com/21309201/42813379-15183a18-89c1-11e8-9354-a314be16422f.jpg)

**Comment by rudky4** [comment]
Funkcia doplnená a dostupná na http://inqooltest.libj.cas.cz/
