### ISSUE TITLE
Chybné "tlačítko" na pozadí

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU#20]
"Tlačítko" na výběr druhu stránky u nové výstavy nelze rozklinout v boxu "Nová obrazovka" na prostředku (na znaménku "+"), jak by se intuitivně dalo očekávat - zde se kurzor mění na čtyřsměrnou šipku - která v tomto případě při kliknutí nic nedělá. V horní třetině celého boxu "Nová obrazovka" se kurzor změní na "ruku" a po kliknutí již vyjede menu - viz obrázek. Tento problém jsem zaznamenal u prohlížeče Mozilla. U Internet Explorer je aktivní celý box.

[Kurzory.pptx](https://github.com/LIBCAS/INDIHU/files/2263283/Kurzory.pptx)

**Comment by rudky4** [comment]
Upraveno dle zadani, prosim o kontrolu (refresh cache prosim)

**Comment by Kolemkoukolem** [comment]
Funguje. Děkuji.
