### ISSUE TITLE
Zoom In

### ISSUE THREAD

**Issue by matulovaklara** [LIBCAS/INDIHU#22]
Lze u funkce Zoom in nastavit dobu prodlevy, po kterou bude zazoomováno na konkrétní prvek? Když je k bodu přidán popisek, tak musí být krátký, aby si ho člověk stihl přečíst. Popř. se může rovnou omezit počet znaků v popisku, aby text nebyl příliš dlouhý. Nebo nechat možnost načtení popisku i po skončení animace (např. v klikacím módu)?

V nápovědě k funkci zoomu se píše, že by to jít mělo (viz: "V tabulce pak k tomuto bodu zájmu vybere úroveň zoomu a délku trvání animace."). Ale já tam nikde tu možnost nevidím. Přikládám printscreeny:

![zoomin](https://user-images.githubusercontent.com/42234445/43889690-24ca5db8-9bc5-11e8-9b77-11a278a952c9.png)

![zoomin-1](https://user-images.githubusercontent.com/42234445/43889691-24e9ad6c-9bc5-11e8-821c-b4d8e4ff9247.png)

Pokud přidám trochu delší text (viz další printscreen), tak ho člověk nestihne přečíst než zmizí.

![zoomin2](https://user-images.githubusercontent.com/42234445/43889720-3670f0fe-9bc5-11e8-8378-79c22a3167af.png)

**Comment by rudky4** [comment]
Doba přiblížení infopointu se počítá na základě atributu přiblížení. Odteď maximální délka infopointu omezena na 100 znaků.
