### ISSUE TITLE
Umístění potvrzovacích tlačítek - jednotit?

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU#25]
Hlavní „potvrzovací“ tlačítko obrazovky (uložit/vybrat/vytvořit atp.) bych intuitivně očekával spíše vpravo dole, ale ne vždy tomu tak je (např. na zde: „Uložit“ vlevo dole, ale „Vytvořit“ vpravo dole)
![obrazek](https://user-images.githubusercontent.com/42305589/43996532-df0c7b38-9dc4-11e8-972f-25ae92813592.png)

**Comment by rudky4** [comment]
tlačitko ULOŽIT bolo presunuté vpravo, NAHLED vlevo
