### ISSUE TITLE
Seznam výstav - roletka "Akce"

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU#28]
Po přepnutí do tohoto režimu a volbě akce vyjede roletka, která by mohla být zarovnaná vlevo a bylo by dobré, pokud by byly vidět všechny hodnoty (zatím jsou jen neúplné texty): 
![obrazek](https://user-images.githubusercontent.com/42305589/43996573-cea0c91a-9dc5-11e8-975e-965ecaec0139.png)
odnoty (zatím jsou jen neúplné texty);

**Comment by rudky4** [comment]
Komponenta prepracovaná do formy modálu.
