### ISSUE TITLE
Seznam výstav - roletka "Akce" - opakované rozbalení

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU#29]
Roletku lze rozbalit u několika projektů zároveň, asi by se to mělo omezit jen na jeden:
![obrazek](https://user-images.githubusercontent.com/42305589/43996581-192d3950-9dc6-11e8-8c08-b0ef43e0f918.png)

**Comment by malinekv** [comment]
Možná bych tutéž roletku zarovnal spíše k pravému dolnímu rohu, nikoli vždy nutně pod nadpis akce,
pak by mohly být na obrazovce vidět všechny možnosti najednou a nebylo by třeba rolovat

nebo ještě spíše bych toto řešil vyskočením okénka doprostřed pracovní plochy (zbytek na pozadí ztmavne) tak, jako jsou řešena různá potvrzovací okénka u nahrávání souborů atp., a roletky obecně pokud možno úplně vypustil

**Comment by rudky4** [comment]
Komponenta prepracovaná do formy modálu.
