### ISSUE TITLE
Náhled PDF 

### ISSUE THREAD

**Issue by krizovj** [LIBCAS/INDIHU#3]
Když nahraju PDF soubor, tak v náhledu je zobrazeno tlačítko "play". Když na ní kliknu, tak zmizí a nic jiného se nestane. Mohlo by se zobrazit to PDF? Nebo se zobrazit nemusí, stačilo by kdyby zmizela ta ikona "play", je to tam tak trochu matoucí.
![pdf](https://user-images.githubusercontent.com/21309201/42813633-f2368350-89c1-11e8-979c-484e9aa60edc.jpg)

**Comment by rudky4** [comment]
bude odstránená ikonka play

**Comment by rudky4** [comment]
@krizovj tlacitko PLAY bolo odstranene, prosim o test a uzavretie.
