### ISSUE TITLE
Výpis výstav - ikona šipky?

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU#30]
Není mi jasný význam šipky v řádku „Výstavy“ (na printscreenu šedivě):
![obrazek](https://user-images.githubusercontent.com/42305589/43996591-76e00e9c-9dc6-11e8-95a8-282cef17ec60.png)

**Comment by rudky4** [comment]
slúži k radeniu výstav, doplnili sme tooltip
