### ISSUE TITLE
Úvod výstavy/Záhlaví - stav výstavy klikací? 

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU#33]
Zde je informace o stavu výstavy, která se po najetí myší tváří, že je klikací, podobně jako „Správa účtu“ vedle ní, ale odkaz nikam nevede; šlo by to nějak upravit (ikona myši se mi v printscreenu neukládá)?

![obrazek](https://user-images.githubusercontent.com/42305589/43996609-dcea67dc-9dc6-11e8-9e12-22c272765055.png)

**Comment by rudky4** [comment]
upraveno, aktualne sa nezobrazuje hover pri prechode na polozku
