### ISSUE TITLE
Úvod výstavy/Tiráž - řazení?

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU#34]
Osoby/Hodnoty nelze nijak řadit, ukládají se v pořadí tak, jak byly zapsány. U delších tiráží může být problém...
![obrazek](https://user-images.githubusercontent.com/42305589/43996625-1a1a91ae-9dc7-11e8-80fc-a363522749f6.png)

**Comment by rudky4** [comment]
Pridaná možnosť filtrovať podľa "Nadpis" alebo "Osoby nebo text". Vľavo nad tabuľkou.
