### ISSUE TITLE
Délka trvání výstavy - grafika +konrola+limitovat?

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU#38]
Pokud je chybně vyplněná délka trvání výstavy 
o	Překrývání nadpisu a hodnoty vlevo i vpravo
o	Systém mě tuto obrazovku nechá uložit i s chybou, typ chyby se objeví jen po najetí myší na červenou řádku
o	Délka výstavy není nijak omezena (asi v pořádku, ale systém schroupne např. i toto číslo 5999999999999999999999999999999999999)
![obrazek](https://user-images.githubusercontent.com/42305589/43996666-d7f469c0-9dc7-11e8-81f3-7852bc94521a.png)

**Comment by rudky4** [comment]
povolené len vkladanie čísel + úprava vizuálu + pridaný rozsah
