### ISSUE TITLE
Náhled stránky

### ISSUE THREAD

**Issue by krizovj** [LIBCAS/INDIHU#4]
Po tom, co uložím stránku a kliknu na "náhled", nic se nestane. Zobrazí se mi jen náhled celé výstavy, pokud si ho zobrazím ze seznamu výstav, ale náhledy jednotlivých stránek mi nefungují. 
Prohlížeč: Chrome (verze 67.0.3396.99).

**Comment by krizovj** [comment]
V Mozille (verze 61.0.1 ) mi ten náhled funguje, ale musím povolit vyskakovací okna, Chrome mi o vyskakovacím oknu nic neřekne a vypadá to, že je to chyba, ptž se tam na chvilku problikne "načítací kolečko". 
Opera (verze 54.0.2952.54) to má jako Mozilla, aspoň mi o tom řekne a po povolení vyskakovacích oken na http://inqooltest.libj.cas.cz už to funguje.
IE (verze 11.0.9600.19080) sice po povolení vyskakovacích oken náhled zobrazí, ale pro změnu úplně zdeformuje obrázky nebo je vůbec neukáže a je tam jen černá obrazovka :) 
Takže to asi je chyba spíš Chromu, že neinformuje o vyskakovacím oknu, tak jen píšu, jak je to u těch ostatních prohlížečů, aby se o tom vědělo.

**Comment by motyc** [comment]
V Chrome dojde k nahlášení blokování okna v řádku URL. Stačí povolit a vše funguje bez problémů.

**Comment by rudky4** [comment]
"náhled se otevírá v nové kartě, ale stejně si to musí uživatel povolit, protože to tak mají asi prohlížeče nastavené. I v chrome jsem měl informaci o zablokování vyskakovacího okna, takže stačilo povolit."
