### ISSUE TITLE
Storno vs. křížek u "vyskakovacích" oken

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU#40]
Není podobně u vyskakovacích oken tlačítko „Storno“ nadbytečné? Má někdy jinou roli než křížek vpravo nahoře, nebo jej vždy pouze duplikuje?
![obrazek](https://user-images.githubusercontent.com/42305589/43996686-4e698716-9dc8-11e8-9d4c-db66e2f43112.png)

**Comment by rudky4** [comment]
Ide o jednotnú funkcionalitu, ale z UX hľadiska a užívateľskej prívetivosti by sme STORNO ponechali.
