### ISSUE TITLE
Název a podnázev v úvodu do kapitoly

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU#42]
Název kapitoly a podnázev se objeví najednou, navrhuji časovou prodlevu - nejprvezapůsobí název, po krátkém zdržení podnázev.

**Comment by rudky4** [comment]
dohodnutých 500ms, pripadne neskor zmeníme

**Comment by rudky4** [comment]
@nnis implementované, 500ms je myslím ok, prosím o feedback

**Comment by nnis** [comment]
Při kontrole se mi to nějak zbláznilo, viz issue #64

**Comment by rudky4** [comment]
@nnis uz je to ok

**Comment by nnis** [comment]
500 ms mi přijde v podstatě tak neznatelné, že mám dojem, že podtitulek jde rovnou bez mezery a pořád rychle.

**Comment by rudky4** [comment]
nastavime 1000ms

**Comment by rudky4** [comment]
done
