### ISSUE TITLE
Záhlaví výstavy - dodat odkazy

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU#43]
Při prohlížení výstavy je uprostřed lišty nahoře název výstavy (čekala bych, že se dostanu buď na HP nebo že to bude fungovat jako menu a zobrazí se mi např. výpis kapitol), zároveň je vlevo název instituce, která výstavu vytvořila, ale také to nic nedělá. nebylo by vhodné vložit do menu políčko, s odkazem na stránky instituce nebo prostě aby to někam vedlo?). Je to prominentní místo na stránce a nic to nedělá, je to pak nevyužité.

**Comment by rudky4** [comment]
Přidáno menu kapitol výstavy a název výstavy odkazuje na úvodní obrazovku výstavy.

**Comment by rudky4** [comment]
tlačítko na zavření odebráno.
Odkaz na Instituci by som nechal ako samostatny rozvoj neskor.
