### ISSUE TITLE
Náhled výstavy

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU#45]
Náhled výstavy už se chová lépe, ale pořád to není stoprocentní - stále náhled funguje jen v případě, že je výstava zveřejněná. Jak to bude do budoucna? To nevypadá dobře, působí to tak, že na rozpracovanou výstavu se již mohou dívat uživatelé; náhled musí fungovat i ve stavu "v přípravě". Náhled mi funguje jen z úvodní stránky editace, ne z jednotlivých stránek - nemohu si proto zkontrolovat stránku, na které aktuálně pracuji, vždy se musím vracet na výpis všech mých rozpracovaných výstav, což je zdlouhavé.

**Comment by Kolemkoukolem** [comment]
Také mám dnes (13.8.) opět problémy se zobrazováním náhledu výstavy. Po vyřešení problému (viz issue č. 5) vše fungovalo. Ještě v pátek jsem něco testoval a dnes na prohlížeči Mozilla mi nejde spustit náhled ani jedné výstavy. Na prohlížeči Google Chrome náhledy fungují.

**Comment by rudky4** [comment]
Ospravedlnujem sa za problem, predam kolegovi k urgentnemu vyrieseniu.

**Comment by Kolemkoukolem** [comment]
V případě jedné obrazovky lze spustit náhled z celkového přehledu, tedy odsud:
![obrazek](https://user-images.githubusercontent.com/42067492/44038611-6e00041a-9f17-11e8-9913-c6b45078e4d5.png)


ale ze stránky s úpravou fotky se po kliknutí na tlačítko "náhled" nic neděje
![obrazek](https://user-images.githubusercontent.com/42067492/44038590-60b8726a-9f17-11e8-8b6d-cbf922ced062.png)

**Comment by rudky4** [comment]
Je ešte nejaká vystáva, ktorej náhľad nefunguje? (ani na ďalší refresh)

**Comment by nnis** [comment]
Prohlížeč Chromium Version 69.0.3497.81 (Official Build) Manjaro Linux (64-bit): U mého účtu náhled funguje jako celek výstavy po refreshi ve stavu Zveřejněná i V přípravě. U jednotlivých stránek tam jen problikne nahrávací kolečko. U chromia mi nenabídlo upravit pop-up preference u jednotlivých stránek. Náhled u jednotlivých stránek mi nefunguje ani ve stavu V přípravě ani u Zveřejněné. 
 
Prohlížeč Firefox Quantum 62.0 (64-bit): U mého účtu náhled funguje jako celek výstavy po refreshi ve stavu Zveřejněná i V přípravě. U jednotlivé stránky se ve stavu V přípravě i ve stavu Zveřejněná po povolení pop-upů náhled fungoval.

**Comment by rudky4** [comment]
@nnis konečne snad funkčné na prvy preklik... v minulosti mi to blblo, kolega odstránil jeden plugin a je to aktuálne v poriadku, prosim o test

**Comment by nnis** [comment]
@rudky4 JO! vypadá to, že to funguje dobře. (chromium i firefox)
