### ISSUE TITLE
Název - (ne)zobrazení

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU#46]
V případě delšího názvu a menšího monitoru se nezobrazuje celý název výstavy.
![obrazek](https://user-images.githubusercontent.com/42067492/44038327-d712ba8e-9f16-11e8-8529-9409348bdf81.png)

**Comment by rudky4** [comment]
Zabezpečime zalomeni textu, je to v poriadku?

**Comment by Kolemkoukolem** [comment]
Ano, zalomení je z mého pohledu ideální řešení. Děkuji.

**Comment by rudky4** [comment]
Opraveno
