### ISSUE TITLE
Tlačítko repreduktoru

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU#48]
Stále poměrně nelogicky působí tlačítko ikonky reproduktoru v náhledovém režimu. Pokud uživatel chce rozbalit menu s rozšiřujícími informacemi, klikne na ikonku se třemi čárkami. Pokud chce menu opět zavřít, musí kliknout (namísto nějakého křížku či stejné ikonky se třemi čárkami) poměrně nelogicky na ikonku reproduktoru.
![obrazek](https://user-images.githubusercontent.com/42067492/44039877-629a28d2-9f1a-11e8-802f-9b7b8869bd96.png)

**Comment by rudky4** [comment]
Reproduktor bol asi v pôvodne indikácia pre pokračovanie v prehrávaní.
Súhlas, že to nie je ideálne. Zajtra navrhneme vhodnú ikonu.

**Comment by rudky4** [comment]
Ikony boli upravené, na úvodnej stránke ostala ikona reproduktoru (aj keď úplne nevidím jej význam).
