### ISSUE TITLE
Náhled výstavy

### ISSUE THREAD

**Issue by krizovj** [LIBCAS/INDIHU#5]
Náhled celé výstavy funguje se mi nezobrazí. Ještě minulý týden to šlo, sice až po F5, ale šlo. Teď se mi náhled vůbec nezobrazí. Výstava se načítá a načte se skoro až do konce a pak se to zasekne a je konec. Čekala jsem 3 minuty a náhled se neotevřel, pořád tam byla jen načítací lišta. 
Zkoušela jsem v Chromu, Mozille, Opeře a IE a všude to bylo stejné (kromě snad IE, kde ta lišta byla nějak podivně zdeformovaná).

**Comment by rudky4** [comment]
Aktuálne odporúčam výstavu zverejniť a následne zobraziť náhľad.
Pracujeme na oprave popísanej chyby.

**Comment by motyc** [comment]
Podle nás (ARÚP) nefunguje ani po zveřejnění, alespoň ne pro výstavu http://inqooltest.libj.cas.cz/view/ZK12018-06-20T141351655Z

I po dlouhém načítání zůstane viset progressbar těsně před koncem
![image](https://user-images.githubusercontent.com/20186892/43640999-4d70768c-9722-11e8-9611-11d41b5303ae.png)

**Comment by rudky4** [comment]
@motyc u danej vystavy je problem s obsahom, analyzujeme problém a dáme vedieť.

**Comment by rudky4** [comment]
@motyc výstavu http://inqooltest.libj.cas.cz/view/ZK12018-06-20T141351655Z/start je možné bez problému načítať, problem bol opravený.
