### ISSUE TITLE
Chybí volba Smazat výstavu v tabulkovém zobrazení

### ISSUE THREAD

**Issue by Ivouch** [LIBCAS/INDIHU#50]
Tabulkové zobrazení:
![image](https://user-images.githubusercontent.com/5199676/45359190-0cf2e180-b5cc-11e8-9eba-33475fd033fc.png)

Zobrazení v mřížce:
![image](https://user-images.githubusercontent.com/5199676/45359232-2b58dd00-b5cc-11e8-9ef0-03671b4ed1b0.png)

**Comment by rudky4** [comment]
opraveno
