### ISSUE TITLE
Klikací mód - konec výstavy?

### ISSUE THREAD

**Issue by matulovaklara** [LIBCAS/INDIHU#51]
Klikací mód: po poslední obrazovce se místo zobrazení obrazovky "konec výstavy" (jako je tomu u prezenčního módu) překlikne výstava zpět na první obrazovku výstavy. Viz printscreeny:

Prezenční mód (správně):
![prezmod1](https://user-images.githubusercontent.com/42234445/45951343-69f68a80-c003-11e8-889f-c3c5765aa1bd.png)
Tuto obrazovku bych očekávala i v klikacím módu:
![prezmod2](https://user-images.githubusercontent.com/42234445/45951344-69f68a80-c003-11e8-9370-4262be46f373.png)

Klikací mód (po najetí na šipku "next" se místo konce výstavy zobrazí opět výstava od začátku):
![klikmod1](https://user-images.githubusercontent.com/42234445/45951366-7d095a80-c003-11e8-898b-3ec9ab312ac0.png)
![klikmod2](https://user-images.githubusercontent.com/42234445/45951367-7d095a80-c003-11e8-8ac3-c64956d58796.png)

**Comment by rudky4** [comment]
Implementovane
