### ISSUE TITLE
Minihra - výběr možností - scrollovátko

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU#56]
Je opravdu nutné to scrollovátko? Je tam, i když je text v odpovědi jen jedno slovo. Chápu jeho použití, když je text dlouhý, ale to rolovátko je tam vždy a nevypadá to dobře. 
![vyber-moznosti](https://user-images.githubusercontent.com/15922183/46720462-debafd00-cc70-11e8-84cb-6da7e561aa3e.png)

Prohlížeč Chromium: Version 69.0.3497.92 (Official Build) Manjaro Linux (64-bit)

**Comment by rudky4** [comment]
Nadbytočné scrollbary odstranené.
