### ISSUE TITLE
Manuál

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU#59]
Manuál je třeba přesunout na GItHub, abychom ho mohli editovat. Zatím je dostupný zde: http://inqooltest.libj.cas.cz/manual/
Potřebujeme aby: 
- bylo možné linkovat do nápovědy v editaci na jednotlivé části. 
- můžeme ho upravovat

Poznámky k manuálu: 
- sjednotit názvosloví, v manuálu se používá slovo divák pro uživatele virtuální výstavy. Probrat na schůzi.

**Comment by rudky4** [comment]
Manuál je dostupný na GH: https://github.com/LIBCAS/INDIHU/tree/manual/manual

Linkovať jednotlivé časti je možné, treba vložiť do manuálu odkazy (napr: #chapter5#section3) a následne do nápovedy v editore vložíme odkaz url/manual#chapter5#section3 - konkrétnu podobu odkazu nechám na Vás.
