### ISSUE TITLE
Náhled obrázku

### ISSUE THREAD

**Issue by krizovj** [LIBCAS/INDIHU#6]
U náhledu obrázku se zobrazuje název, typ a velikost. Bylo by možné, aby se tam zobrazoval také údaj o rozlišení? V manuálu se vždycky totiž doporučuje nějaké určité rozlišení, tak aby si to mohl člověk ještě ověřit.

**Comment by rudky4** [comment]
@krizovj rozlíšenie sa zobrazí po kliknutí na náhľad obrázku (aktuálne najefektívnejšie riešenie na implementáciu) 

![image](https://user-images.githubusercontent.com/7311447/43896203-462da678-9bd8-11e8-99a0-844112efc1e4.png)

Prosím o test a prípadne uzavretie
