### ISSUE TITLE
Nahrávání souborů

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU#60]
Ani do jedné (ze tří) z mých testovacích výstav nejde nahrát žádný soubor. Vytvořil jsem novou výstavu a ani tam nelze žádný soubor (obrázek jpg nahrát). Jedná se o nové soubory i soubory, které jsem již pro jinou testovací výstavu použil a bez problému nahrál. Nelze nahrát ani na prohlížeči Mozilla (Fierfox Quantum 62.0.3 (64 bitů)) ani na Internet Explorer 11 (verze 11.0.9600.19155). Problém přetrvává od pátku 5.10. Předtím jsem žádný problém s nahráváním neměl.

**Comment by rudky4** [comment]
@Kolemkoukolem bude problem s pravami zapisu na disk, upravime asap

**Comment by rudky4** [comment]
@Kolemkoukolem upload už funguje.
