### ISSUE TITLE
Horní lišta v editaci

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU#61]
Shodli jsme s Ivem a Ondřejem, že je trochu nejasný přechod od hlavní lišty do lišty, kde již edituji jednotlivé záložky ke stránkám (např. na stránce Úvod výstavy jsou to záložky Název, popis audio / Tiráž / Dokumenty) . 
Bylo by možné to trochu oddělit? Je to jednolitý modrý pruh. Jednotlivé záložky u stránky totiž nejsou na první pohled úplně vidět. Když člověk rozhraní zná, není to problém, ale zpočátku se v tom špatně orientuje. 
Zároveň je tam ukazatel v podobě tenoučké světle modré lišty, kde se zrovna nacházím, ale není tam patrné, že pak mohu přejít ještě ke dvěma dalším záložkám. 

![lista](https://user-images.githubusercontent.com/15922183/46737566-1db27800-cc9c-11e8-9f9e-99f9b117966b.png)

Prohlížeč Chromium: Version 69.0.3497.92 (Official Build) Manjaro Linux (64-bit)

**Comment by nnis** [comment]
Ta linka podle mě funguje dobře. 
Ten ukazatel záložky (název / tiráž / dokumenty) je hodně nepatrná, nešlo by to udělat tak, že celá pole pod názvem by zesvětlalo? Nebo aby měla ještě svislé bočnice, takže by z toho byl patrnější obdélník?
Díky!

**Comment by rudky4** [comment]
@nnis upraveno, prosim o feedback

**Comment by nnis** [comment]
Za mě rozhodně lepší, díky! Jen mě ještě napadá detail, možná bych ještě přidala spodní tenkou modrou linku, aby to byl pořád viditelný obdélník a nesplývalo to tolik s bílým pozadím stránky pod tím, i když "ty dvě bílé" nejsou úplně stejné.

**Comment by rudky4** [comment]
@nnis pozadí položky menu upraveno tak, aby nesplývalo s pozadím stránky a nebyl potřeba okraj, test prosim

**Comment by nnis** [comment]
Bezva, funguje to.
