### ISSUE TITLE
Progress bar na kazdu stranku - najst riesenie

### ISSUE THREAD

**Issue by rudky4** [LIBCAS/INDIHU#63]
Z uzivatelskeho hladiska informovat o stave na danej obrazovke, az nedojde k pocitu zaseknutia.

**Comment by rudky4** [comment]
přidán progress bar... kvůli tomu je odteď přidáváno id při vytvoření obrazovky (v některých případech nemusí pro staré obrazovky progress bar fungovat na 100% správně), cc @nnis

**Comment by rudky4** [comment]
@nnis barva upravena. U stránky s externím obrázkem progress bar ukazuje dobu zobrazení stránky, která bude zadána v editoru... délka videa z youtube na něj nemá vliv. Jeli na této stránce nevhodný, může být odstraněn, stejně jako u her.

**Comment by nnis** [comment]
@rudky4 barva je mnohem lepší. Díky za vysvětlení, jak se to chová s videem. U her bych časovač nedávala. 

K tomu mě napadá další věci, co s tím souvisí.  U videa mi to vlastně ještě přijde logické - vidím, jak dlouhý mám čas si video pustit, takže tam bych to asi nechala, jenže když tam dám embed mapu, tak co najednou s tím? To pak nedává smysl nebo tam mám dát delší čas, aby si s tou mapou uživatel pohrál. Ta mapa funguje vlastně víc jako hra - je to na uživateli, zda jí bude prozkoumávat a jak dlouho. A když si s ní nechce hrát, jak se posune dál? To samé s videem, když video skončí, uživatel tam vlastně zůstane trčet, protože obrazovka se nepřesune k další automaticky, šipky na posun tam nejsou a když jsem to zkoušela, překlikla jsem se do textového módu a takovýhle byl výsledek: 
![video-posun-dal](https://user-images.githubusercontent.com/15922183/48539807-89e65400-e8b8-11e8-9356-20409055a36f.png)
- žádné šipky. Když mám ale od začátku textový mód, ty šipky u videa tam jsou. 
Navíc překlikávání do textového módu a zase zpátky narušuje flow a plynulost celé výstavy?

**Comment by rudky4** [comment]
@nnis reakcia z vyvoja:
"U her se progress bar nenachází. Šipky jsou v textovém módu vždy, když se jedná o prohlížeč celé výstavy (ne o prohlížeč jedné obrazovky, který se otevře po kliknutí na náhled u konkrétní obrazovky - tam šipky nejsou, protože je načtena pouze jedna obrazovka). Při vložení embed mapy v obrazovce s externím objektem se počítá hodnota progress baru (stejně jako u ostatních obrazovek) z délky trvání výstavy, kterou uživatel zadá nebo se získá z audia obrazovky. Uživatel má tedy v tomto případě zobrazenou mapu jen po dobu, která je zadána a nemůže se do té doby posunout dále, pokud se nepřesune do textového módu (progress bar má tedy smysl). U videa to samé... v textovém módu se může posouvat jak chce (nemusí čekat na skončení videa), pokud se jedná o prohlížení celé výstavy a ne jedné obrazovky. V klasickém módu musí počkat, než uběhne nastavená doba (než je plný progress bar)... uživatel by tedy měl zajistit, aby doba zobrazení obrazovky (případně audio obrazovky) byla +- stejně dlouhá, jako je video."

Ak to nie je aktualne blocker, tuto issue by som uzavrel a nove pripomienky riesil zvlast v detailnejsich issues.

**Comment by nnis** [comment]
Ok, můžeme to uzavřít, chová se to tedy tak, jak se to má chovat, otázkou je, jestli je toto chování žádoucí. Bude to třeba probrat v širším týmu, my s Ivem s tím trochu problém máme. Díky.
