### ISSUE TITLE
Úvod do kapitoly

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU#64]
Nějak se mi to zbláznilo, líp to nedovedu popsat. Kontrolovala jsem prodlevu mezi titulkem a podtitulkem (viz issue #42) a jednak mi nehraje hudba (zkoušela jsem 2 různé písničky ve formátu mp3) a pak se stalo toto (poslední znak se odvíjel pořád dál až název i podnázev kapitoly ujel nahoru a byly tam jen ty otazníky):
 
![indihu1](https://user-images.githubusercontent.com/15922183/47425541-ec9d7180-d78a-11e8-981c-35389d6608f1.png)

![indihu](https://user-images.githubusercontent.com/15922183/47425543-ec9d7180-d78a-11e8-9afa-2b727f632c1b.png)

Prohlížeč Chromium: Version 69.0.3497.100 (Official Build) Arch Linux (64-bit)

**Comment by rudky4** [comment]
@nnis problém s textem vyřešen... hudba se nepřehrávala nejspíše proto, že nedošlo k interakci uživatele se stránkou, což způsobilo zablokování hudby od prohlížeče (uživatel musí nejdříve například kliknout někam do stránky v prohlížeči než se načte)

**Comment by nnis** [comment]
Teď už dobré
