### ISSUE TITLE
Najdi na obrázku

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU#65]
Možná je to jen nejasnost, ale u jiných her má uživatel možnost označit svůj tip pomocí tlačítka hotovo, tady ne - uživatel jednou klikne a rovnou je to definitivní a zobrazí se mu výsledek. neměl by i zde mít uživatel možnost se rozmyslet? Mám dojem, že by se mohl "omylem ukliknout" a tak vlastně hru prošvihnout a bez tlačítka hotovo jeho tip není tak úplně vědomý. 

![hledej-na-obrazku](https://user-images.githubusercontent.com/15922183/47504679-02836300-d86d-11e8-86d3-2a608b69b46b.png)

Prohlížeč Chromium: Version 69.0.3497.100 (Official Build) Arch Linux (64-bit)

**Comment by rudky4** [comment]
@nnis má se upravit tak, aby se po kliknutí na obrázek (a umístění vlajky) muselo ještě kliknout na tlačítko hotovo, podobně, jako u jiných her?

**Comment by nnis** [comment]
Jestli to i vy shledáváte logickým, pak ano, tak jsem to myslela. Protože to by také znamenalo, že mohu kliknout třeba dvakrát a označit až ten druhý tip jako konečný. Je to tak?

**Comment by rudky4** [comment]
@nnis malo by byt upravene, prosim o test

**Comment by nnis** [comment]
funguje, bezva
