### ISSUE TITLE
Přihlášení do editoru - pořadí položek

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU#70]
Teď jsou položky v procesu přihlášení 1. Registrovat, 2. Resetovat heslo, 3. Přihlásit. Vzhledem k tomu, že se registruji jednou, ale přihlašuji se opakovaně, nebylo by vhodnější upravit pořadí na: 1. Přihlásit, 2. Registrovat, 3. Resetovat heslo, ale na první místě bylo to, které bude ve výsledku nejpoužívanější?

**Comment by rudky4** [comment]
upravene
