### ISSUE TITLE
Přejmenování obrázků v minihře Hádej velikost

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU#71]
Prosím o přejmenování: 
Levý obrázek - Obrázek referenčního předmětu
Pravý obrázek - Obrázek porovnávaného předmětu

![hadej-velikost](https://user-images.githubusercontent.com/15922183/49285432-adec8c80-f497-11e8-86f0-d349a71b3c37.png)

**Comment by rudky4** [comment]
upravene
