### ISSUE TITLE
Zobrazení výběru animace - úvod kapitoly

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU#72]
Prosím o úpravu zobrazení výběru z možností animace na Úvodu výstavy tak, aby se tam zobrazily celé názvy možností a ne jen první tři písmena, to je pak nesrozumitelné. 

![animace-obr](https://user-images.githubusercontent.com/15922183/49292456-96200300-f4ad-11e8-9b9c-343cd66114a6.png)

Chromium: Version 70.0.3538.110 (Official Build) Manjaro Linux (64-bit)

**Comment by rudky4** [comment]
zobrazenie opravené
