### ISSUE TITLE
Klávesová zkratka pro náhled

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU#74]
Navrhuji se zamyslet, jestli ke klávesovým zkratkám ESC, Shift+Ctrl ještě nepřidat třeba F5 pro náhled. Bylo by to taky fajn.

**Comment by rudky4** [comment]
Neviem, či je ideálne nahradiť natívnu funkcionalitu tlačítka F5 - refresh stránky. 
Môžeme však vymyslieť niečo alternatívne, Ctrl+P (Preview) aj keď to sa používa na Print.

**Comment by rudky4** [comment]
pridané Ctrl+P (Preview)

**Comment by nnis** [comment]
Skvělé, funguje díky.
