### ISSUE TITLE
Minihra Dokresli - reset

### ISSUE THREAD

**Issue by krizovj** [LIBCAS/INDIHU#8]
Nejdříve se objeví první obrázek, něco do něj dokreslím. Stisknu tlačítko "hotovo" a objeví se obrázek "výsledek". Když následně stisknu tlačítko "Reset", tak pouze zmizí dokreslená část, ale zůstane tam obrázek "výsledek". Nemělo by se to vrátit úplně na začátek, abych to mohla zkusit znovu dokreslit? 
Pokud ne a takhle je to správně, tak se omlouvám.

**Comment by rudky4** [comment]
Tlačítko reset bolo odstránené (bolo zobrazené zbytočne navyše)
