### ISSUE TITLE
Obrázky se deformují

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU#9]
Obrázky se při zobrazení deformují (nezachovávají původní poměry stran).

Původní:
![image](https://user-images.githubusercontent.com/20186892/43641534-5e44be80-9724-11e8-9cd0-86834882b3f2.png)

Při zobrazení výstavy:
![image](https://user-images.githubusercontent.com/20186892/43641545-69f432b0-9724-11e8-8454-e67ed75c2567.png)

**Comment by rudky4** [comment]
Opraveno 

![image](https://user-images.githubusercontent.com/7311447/43900756-0793a3b4-9be6-11e8-9612-22ea9934bc7b.png)
